"""inicial

Revision ID: 0c0679003d9a
Revises: 
Create Date: 2026-09-11 18:32:03.838683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c0679003d9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ruta', sa.String(length=200), nullable=False),
    sa.Column('listo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('max_proyectos', sa.Integer(), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('dominio_personalizado', sa.String(length=150), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_empresa', 'numero_documento', name='uq_cliente_empresa_doc')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_empresa', 'slug', name='uq_proyecto_empresa_slug')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_empresa', 'clave', name='uq_rol_empresa_clave')
    )
    op.create_table('etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('partida_registral', sa.String(length=50), nullable=False),
    sa.Column('sunarp_url', sa.String(length=300), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_proyecto', 'partida_registral', name='uq_etapa_proyecto_partida')
    )
    op.create_table('rol_modulo',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rol', 'id_modulo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=50), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('manzanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_etapa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_etapa'], ['etapas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_etapa', 'nombre', name='uq_manzana_etapa_nombre')
    )
    op.create_table('metas_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('meta_lotes', sa.Integer(), nullable=True),
    sa.Column('meta_monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_proyecto', 'periodo', name='uq_meta_usuario_proyecto_periodo')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_usuario_destino', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_usuario_leido', 'notificaciones', ['id_usuario_destino', 'leido'], unique=False)
    op.create_table('usuario_empresa',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_empresa')
    )
    op.create_table('usuario_modulo_permiso',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_modulo')
    )
    op.create_table('usuario_proyecto',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_proyecto')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_manzana', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('ubicacion_lote', sa.String(length=50), nullable=True),
    sa.Column('perimetro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_m2_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_total_base', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_m2_contado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_total_contado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inicial_financiado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monto_financiado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_total_financiado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('libre', 'vendido', 'bloqueado', 'separado', name='estado_lote_enum'), nullable=False),
    sa.Column('partida_registral', sa.String(length=50), nullable=True),
    sa.Column('sunarp_url', sa.String(length=300), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('mapa_x', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mapa_y', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_manzana'], ['manzanas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_proyecto', 'codigo', name='uq_lote_proyecto_codigo')
    )
    op.create_index('idx_lotes_estado', 'lotes', ['id_proyecto', 'estado'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=30), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('fecha_contrato', sa.Date(), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inicial_abonado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_abono', sa.Date(), nullable=True),
    sa.Column('tiene_interes', sa.Boolean(), nullable=True),
    sa.Column('forma_pago', sa.Enum('contado', 'credito', name='forma_pago_enum'), nullable=False),
    sa.Column('saldo_financiado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numero_cuotas', sa.Integer(), nullable=True),
    sa.Column('tea', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tcea', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tem', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fecha_inicio_interes', sa.Date(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('frecuencia_cuota', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.Enum('vigente', 'cancelado', 'moroso', 'anulado', name='estado_contrato_enum'), nullable=False),
    sa.Column('sistema_contable_status', sa.String(length=20), nullable=True),
    sa.Column('id_usuario_registro', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_registro'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_empresa', 'numero_contrato', name='uq_contrato_empresa_numero')
    )
    op.create_index('idx_contratos_lote', 'contratos', ['id_lote'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.Column('origen', sa.Enum('web', 'whatsapp', 'facebook', 'instagram', 'referido', 'otro', name='origen_lead_enum'), nullable=True),
    sa.Column('estado', sa.Enum('nuevo', 'contactado', 'en_seguimiento', 'convertido', 'descartado', name='estado_lead_enum'), nullable=False),
    sa.Column('id_ejecutivo_asignado', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_ejecutivo_asignado'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_estado', 'leads', ['id_proyecto', 'estado'], unique=False)
    op.create_table('lote_estado_historial',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('libre', 'vendido', 'bloqueado', 'separado', name='estado_lote_enum'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('libre', 'vendido', 'bloqueado', 'separado', name='estado_lote_enum'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('es_portada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_clientes',
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('titular', 'conyuge', 'copropietario', name='rol_cliente_contrato_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_contrato', 'id_cliente')
    )
    op.create_table('cronograma_pagos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('fecha_pago_programada', sa.Date(), nullable=False),
    sa.Column('capital', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amortizacion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interes_mensual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interes_acumulado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monto_cuota', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requiere_pago', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagada', 'vencida', 'parcial', name='estado_cuota_enum'), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_pago_real', sa.Date(), nullable=True),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_contrato', 'numero_cuota', name='uq_cronograma_contrato_cuota')
    )
    op.create_index('idx_cronograma_fecha_estado', 'cronograma_pagos', ['fecha_pago_programada', 'estado'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tipo_documento', sa.Enum('minuta', 'certificado', 'comprobante_pago', 'dni', 'contrato_firmado', 'otro', name='tipo_documento_enum'), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=True),
    sa.Column('url_archivo', sa.String(length=300), nullable=False),
    sa.Column('es_publico', sa.Boolean(), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_seguimientos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lead', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nota', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_lead'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_mensajes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lead', sa.BigInteger(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('numero_telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('tipo_mensaje', sa.String(length=20), nullable=True),
    sa.Column('estado_envio', sa.String(length=20), nullable=True),
    sa.Column('wa_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_lead'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_cuota', sa.BigInteger(), nullable=True),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('numero_operacion', sa.String(length=50), nullable=True),
    sa.Column('comprobante_url', sa.String(length=300), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['id_cuota'], ['cronograma_pagos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('whatsapp_mensajes')
    op.drop_table('lead_seguimientos')
    op.drop_table('documentos')
    op.drop_index('idx_cronograma_fecha_estado', table_name='cronograma_pagos')
    op.drop_table('cronograma_pagos')
    op.drop_table('contrato_clientes')
    op.drop_table('lote_imagenes')
    op.drop_table('lote_estado_historial')
    op.drop_index('idx_leads_estado', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_contratos_lote', table_name='contratos')
    op.drop_table('contratos')
    op.drop_index('idx_lotes_estado', table_name='lotes')
    op.drop_table('lotes')
    op.drop_table('usuario_proyecto')
    op.drop_table('usuario_modulo_permiso')
    op.drop_table('usuario_empresa')
    op.drop_index('idx_notif_usuario_leido', table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_table('metas_ventas')
    op.drop_table('manzanas')
    op.drop_table('usuarios')
    op.drop_table('rol_modulo')
    op.drop_table('etapas')
    op.drop_table('roles')
    op.drop_table('proyectos')
    op.drop_table('clientes')
    op.drop_table('empresas')
    op.drop_table('planes')
    op.drop_table('modulos')
    # ### end Alembic commands ###
